# Generated by Django 2.2 on 2021-05-05 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_auto_20210505_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='address2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='first_name',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2, 'Please make at least 2 charactors')]),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Please make at least 2 charactors')]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='address2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='first_name',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2, 'Please make at least 2 charactors')]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Please make at least 2 charactors')]),
        ),
    ]
