# Generated by Django 2.2 on 2021-05-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_auto_20210505_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
    ]
