# Generated by Django 2.2 on 2021-05-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_auto_20210505_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='productcart',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='productcart',
            old_name='product_id',
            new_name='product',
        ),
    ]
