# Generated by Django 2.2 on 2021-05-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_auto_20210506_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(null=True),
        ),
    ]
