# Generated by Django 2.2 on 2021-05-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_auto_20210508_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
